### ISSUE TITLE
Running qnn-onnx-converter gives error: No module: libPyIrGraph38 

### ISSUE THREAD

**Issue by Arya-Ayra** [quic/qidk#33]
I am using Ubuntu 20.04 OS, and installed the SDK via docker-enviorment [(snpe-docker)](https://github.com/quic/qidk/blob/master/Tools/snpe-docker/README.md) 
While trying to convert the model to FP_32 model using the steps mentioned [here](https://github.com/quic/qidk/tree/master/Examples/QNN-Model-Example-EnhancementGAN#steps-to-convert-model-to-fp_32-model) I get the error:

```
Traceback (most recent call last):
  File "/workspace/snpe/bin/x86_64-linux-clang/qnn-onnx-converter", line 12, in <module>
    from qti.aisw.converters import onnx as onnx_frontend
  File "/workspace/snpe/lib/python/qti/aisw/converters/onnx/__init__.py", line 8, in <module>
    from .onnx_to_ir import OnnxConverterFrontend
  File "/workspace/snpe/lib/python/qti/aisw/converters/onnx/onnx_to_ir.py", line 14, in <module>
    from qti.aisw.converters.common.utils import code_to_message
  File "/workspace/snpe/lib/python/qti/aisw/converters/common/__init__.py", line 87, in <module>
    raise e
  File "/workspace/snpe/lib/python/qti/aisw/converters/common/__init__.py", line 40, in <module>
    import libPyIrGraph38 as ir_graph
ModuleNotFoundError: No module named 'libPyIrGraph38'

```

The error is encountered because the docker-enviornment setup does not install the Python dependencies for the file: [/workspace/snpe/lib/python/qti/aisw/converters/common/__init__.py]

There are several other modules that the file requires:

```
          from . import libPyIrGraph36 as ir_graph
            from . import libPyIrSerializer36 as qnn_ir
            from . import libPyIrJsonSerializer36 as json_serializer
            from . import libPyIrJsonDeserializer36 as json_deserializer
            from . import libPyIrQuantizer36 as ir_quantizer
            from . import libPyLightWeightIrQuantizer36 as light_weight_ir_quantizer
            from . import libPyIrEncodingsJsonSerializer36 as encodings_json_serializer

```

Please provide a solution to the above issue.

**Comment by quic-rneti** [comment]
Hello @Arya-Ayra - We are modifying our docker file for latest SDK version. It will be updated in open source repo in few days.

**Comment by Arya-Ayra** [comment]
I was facing issues with the Dockerfile too, here is the solution that worked to resolve the below errors. I have attached the modified [Dockerfile](https://github.com/user-attachments/files/16927021/Dockerfile.txt). 
I hope this helps.

Error were due to :
```
FROM ubuntu:20.04
FROM python:3.8

When you use FROM more than once, Docker treats each FROM as starting a new stage in a multi-stage build. As a result, only the last FROM instruction (in this case, FROM python:3.8) is relevant to the final image.
```

As I am using OS: Ubuntu 20.04, hence I don't need the base image for Ubuntu: 20.04 in the dockerfile.
ON trying to resolve this error I faced another error regarding:

```
ResolutionTooDeep: 200000, is related to the dependency resolution process in pip. It occurs when the dependency graph is too complex or has circular dependencies, causing pip to exceed its maximum allowed resolution depth.
```

Hence I modified the Dockerfile to Use the --use-deprecated=legacy-resolver Flag,  Install Packages in Smaller Batches.

The [Dockerfile](https://github.com/user-attachments/files/16927021/Dockerfile.txt).  that works for me is attached.

**Comment by Arya-Ayra** [comment]
Also, looking into the error regarding Python Lib:libPyIrGraph38 not found, I understood that this is not a python lib, but written by Qualcomm and should have been present in SNPE directory. This file is present for Window platform, but missing for linux x86_64, architecture.

**Comment by quic-rneti** [comment]
Updated docker is published yesterday. Pls check and get back

**Comment by Arya-Ayra** [comment]
Where can I get the latest version for QNN SDK?
The README say's:
```
This docker file can be used on SNPE and QNN Versions: 2.25 and above
```
 But the version available for download is 2.22.6: [Link](https://www.qualcomm.com/developer/software/neural-processing-sdk-for-ai?redirect=qdn)
 
 Can you provide the link to download the latest: 22.6.0 version of the SDK.
 Thank you.

**Comment by quic-vraidu** [comment]
In QIDK/Readme, Section: Download AI SDK contains link to SDK.

**Comment by Sathishkumark6130** [comment]
Hi @quic-rneti and @quic-vraidu,

I installed the Qualcomm AI SDK  version 2.29.0.241129 in Qualcomm software center website.  While trying to convert the model, I got an following issue.

Traceback (most recent call last): File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/__init__.py", line 75, in <module> from . import libPyIrGraph38 as ir_graph ImportError: cannot import name 'libPyIrGraph38' from partially initialized module 'qti.aisw.converters.common' (most likely due to a circular import) (/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/__init__.py) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/bin/x86_64-linux-clang/qnn-tensorflow-converter", line 14, in <module> from qti.aisw.converters.tensorflow.tf_to_ir import TFConverterFrontend File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/tensorflow/tf_to_ir.py", line 14, in <module> import qti.aisw.converters.common.utils.code_to_message as code_to_message File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/__init__.py", line 95, in <module> raise e File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/__init__.py", line 43, in <module> import libPyIrGraph38 as ir_graph ModuleNotFoundError: No module named 'libPyIrGraph38'


looking into the error regarding Python Lib:libPyIrGraph38 not found, I understood that this is not a python lib, but written by Qualcomm and should have been present in QNN directory. This file is present for Window platform, but missing for linux x86_64, architecture.

Please provide a solution to the above issue..

Thanks and Regards 
Sathishkumar K
