### ISSUE TITLE
Running qnn-tensorflow-convertor gives error:No module found libPyIrGraph38.

### ISSUE THREAD

**Issue by Sathishkumark6130** [quic/qidk#55]
I installed the Qualcomm AI SDK version 2.29.0.241129 in Qualcomm software center website. While trying to convert the model, I got an following issue.

Traceback (most recent call last): File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/init.py", line 75, in from . import libPyIrGraph38 as ir_graph ImportError: cannot import name 'libPyIrGraph38' from partially initialized module 'qti.aisw.converters.common' (most likely due to a circular import) (/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/init.py) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/bin/x86_64-linux-clang/qnn-tensorflow-converter", line 14, in from qti.aisw.converters.tensorflow.tf_to_ir import TFConverterFrontend File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/tensorflow/tf_to_ir.py", line 14, in import qti.aisw.converters.common.utils.code_to_message as code_to_message File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/init.py", line 95, in raise e File "/u/ee212702/GPU_1/v2.29.0.241129/qairt/2.29.0.241129/lib/python/qti/aisw/converters/common/init.py", line 43, in import libPyIrGraph38 as ir_graph ModuleNotFoundError: No module named 'libPyIrGraph38'

looking into the error regarding Python Lib:libPyIrGraph38 not found, I understood that this is not a python lib, but written by Qualcomm and should have been present in QNN directory. This file is present for Window platform, but missing for linux x86_64, architecture.

Please provide a solution to the above issue..

Thanks and Regards
Sathishkumar K

**Comment by quic-vraidu** [comment]
Is this issue observed with any specific example in QIDK github?
Can you share the list of steps you are tried resulting to this error?
